branches:
  only:
    - master

language: objective-c
osx_image: xcode8.3

env:
  global:
    - NODE_VERSION=stable
    

before_install:
  - set -e
  - brew update
  - brew install yarn
  - brew outdated node || brew upgrade node
  - brew outdated yarn || brew upgrade yarn
  
  
install:
  - yarn install
  - yarn add codecov --dev

script:
  - yarn run test
  - detox build --configuration ios.sim.release
  - detox test --configuration ios.sim.release --cleanup

after_success:
  - codecov