branches:
  only:
    - master
    
env:
  global:
    - NODE_VERSION=stable
  
matrix:
  include:
    - language: node_js
      node_js: 8
      cache:
        yarn: true
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn install
        - yarn add codecov --dev
      script:
        - yarn install
        - yarn test
      after_success:
        - codecov
        
    - language: objective-c
      os: osx
      osx_image: xcode8.3
      cache:
        - yarn
      before_install:
        - brew update
        - brew install node
        - brew install yarn
        - brew outdated node || brew upgrade node
        - brew outdated yarn || brew upgrade yarn
        - brew tap wix/brew
        - brew install --HEAD applesimutils
      install:
        - npm install -g react-native-cli
        - npm install -g detox-cli
        
        - yarn install
      script:
        - detox build --configuration ios.sim.release
        - detox test --configuration ios.sim.release --cleanup