branches:
  only:
    - master
    
env:
  global:
    - NODE_VERSION=stable
  
matrix:
  include:
    - language: node_js
      node_js: 8
      cache:
        yarn: true
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn install
        - yarn add codecov --dev
      script:
        - yarn install
        - yarn test
      after_success:
        - codecov
        
    - language: objective-c
      os: osx
      osx_image: xcode8.3
      cache:
        - yarn
      before_install:
        - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - brew update
        - brew install yarn || brew upgrade yarn
        - brew tap wix/brew
        - brew install --HEAD applesimutils || brew upgrade --HEAD applesimutils
      install:
        - npm install -g react-native-cli
        - npm install -g detox-cli
        
        - yarn install
      script:
        - detox build --configuration ios.sim.release
        - detox test --configuration ios.sim.release --cleanup
        
    - language: android
      sudo: required
      os: osx
      osx_image: xcode8.3
      jdk: oraclejdk8
      before_script:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
        
        - android-update-sdk --components=sys-img-$ABI-$API --accept-licenses='android-sdk-license-[0-9a-f]{8}'
        - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
        - emulator -avd test -no-skin -no-audio -no-window -gpu off &
        - android-wait-for-emulator
        - adb devices
        - adb shell input keyevent 82 &
      cache:
        directories:
          - $HOME/.yarn-cache
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      before_install:
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - node --version
        - npm install -g yarn
      install:
        - npm install -g react-native-cli
        - npm install -g detox-cli
        
        - yarn install
      android:
        components:
          - platform-tools
          - tools
           
          - build-tools-23.0.1
          
          - android-23
          - android-21

          - extra-google-m2repository
          - extra-android-m2repository
          - sys-img-armeabi-v7a-android-21
      script:
        - react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
        - detox build --configuration android.emu.release
        - detox test --configuration android.emu.release --cleanup
      