branches:
  only:
    - master
    
env:
  global:
    - NODE_VERSION=stable

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  
install:
  - yarn install
  - yarn add codecov --dev
  
matrix:
  include:
    - language: node_js
      node_js: 8
      cache:
        yarn: true
      script:
        - yarn install
        - yarn test
        
    - language: objective-c
      os: osx
      osx_image: xcode8.3
      cache:
        - yarn
      before_install:
        - brew update
        - brew install yarn
        - brew outdated node || brew upgrade node
        - brew outdated yarn || brew upgrade yarn
      before_script:
        - sudo easy_install virtualenv
        - virtualenv ~/virtualenv
        - source ~/virtualenv/bin/activate
      script:
        - yarn test

after_success:
  - codecov