export const FETCHING_ITEMS = 'FETCHING_ITEMS'

export const RECEIVED_ITEMS = 'RECEIVED_ITEMS'

export const ERROR_ON_FETCHING_ITEMS = 'ERROR_ON_FETCHING_ITEMS'

export const FETCHING_MORE_ITEMS = 'FETCHING_MORE_ITEMS'

export const RECEIVED_MORE_ITEMS = 'RECEIVED_MORE_ITEMS'

export const ERROR_ON_FETCHING_MORE_ITEMS = 'ERROR_ON_FETCHING_MORE_ITEMS'
